// <auto-generated />
using System;
using Casan_IT15_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Casan_IT15_Project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260426184726_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Casan_IT15_Project.Models.Backup", b =>
                {
                    b.Property<int>("BackupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackupId"));

                    b.Property<string>("BackupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BackupId");

                    b.ToTable("Backups");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            Address = "123 Industrial Ave, Manila, Philippines",
                            CompanyName = "OptiFlow Manufacturing Inc.",
                            ContactEmail = "admin@optiflow.com",
                            ContactPhone = "+63-912-345-6789",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Industry = "Manufacturing",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Defect", b =>
                {
                    b.Property<int>("DefectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DefectId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CorrectiveAction")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DefectCount")
                        .HasColumnType("int");

                    b.Property<string>("DefectType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("InspectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DefectId");

                    b.HasIndex("InspectionId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.InventoryItem", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRestockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int");

                    b.Property<int>("QuantityReserved")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WarehouseLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InventoryId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            InventoryId = 1,
                            BatchNumber = "BATCH-2026-001",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaterialId = 1,
                            QuantityOnHand = 200,
                            QuantityReserved = 50,
                            WarehouseLocation = "Warehouse A-1"
                        },
                        new
                        {
                            InventoryId = 2,
                            BatchNumber = "BATCH-2026-002",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaterialId = 2,
                            QuantityOnHand = 350,
                            QuantityReserved = 100,
                            WarehouseLocation = "Warehouse A-2"
                        },
                        new
                        {
                            InventoryId = 3,
                            BatchNumber = "BATCH-2026-003",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaterialId = 3,
                            QuantityOnHand = 45,
                            QuantityReserved = 10,
                            WarehouseLocation = "Warehouse B-1"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MinimumOrderQty")
                        .HasColumnType("int");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UnitOfMeasure")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaterialId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("MaterialCode")
                        .IsUnique();

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaterialCode = "MAT-001",
                            MaterialName = "Steel Sheet 4x8",
                            MinimumOrderQty = 10,
                            ReorderLevel = 50,
                            SupplierName = "PhilSteel Corp",
                            UnitCost = 1500.00m,
                            UnitOfMeasure = "Sheet"
                        },
                        new
                        {
                            MaterialId = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaterialCode = "MAT-002",
                            MaterialName = "Aluminum Bar 2m",
                            MinimumOrderQty = 25,
                            ReorderLevel = 100,
                            SupplierName = "MetalWorks PH",
                            UnitCost = 850.00m,
                            UnitOfMeasure = "Piece"
                        },
                        new
                        {
                            MaterialId = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaterialCode = "MAT-003",
                            MaterialName = "Industrial Paint - Blue",
                            MinimumOrderQty = 5,
                            ReorderLevel = 30,
                            SupplierName = "ColorTech Inc",
                            UnitCost = 320.00m,
                            UnitOfMeasure = "Liter"
                        },
                        new
                        {
                            MaterialId = 4,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaterialCode = "MAT-004",
                            MaterialName = "Welding Wire 1.2mm",
                            MinimumOrderQty = 5,
                            ReorderLevel = 20,
                            SupplierName = "WeldSupply Co",
                            UnitCost = 2200.00m,
                            UnitOfMeasure = "Roll"
                        },
                        new
                        {
                            MaterialId = 5,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MaterialCode = "MAT-005",
                            MaterialName = "Rubber Gasket Set",
                            MinimumOrderQty = 50,
                            ReorderLevel = 200,
                            SupplierName = "RubberTech PH",
                            UnitCost = 180.00m,
                            UnitOfMeasure = "Set"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.MrpRecord", b =>
                {
                    b.Property<int>("MrpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MrpId"));

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RequiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("MrpId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("MrpRecords");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermissionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Module")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            Description = "View user list",
                            Module = "Users",
                            PermissionName = "Users.View"
                        },
                        new
                        {
                            PermissionId = 2,
                            Description = "Create new users",
                            Module = "Users",
                            PermissionName = "Users.Create"
                        },
                        new
                        {
                            PermissionId = 3,
                            Description = "Edit users",
                            Module = "Users",
                            PermissionName = "Users.Edit"
                        },
                        new
                        {
                            PermissionId = 4,
                            Description = "Delete users",
                            Module = "Users",
                            PermissionName = "Users.Delete"
                        },
                        new
                        {
                            PermissionId = 5,
                            Description = "View production schedules",
                            Module = "Production",
                            PermissionName = "Production.View"
                        },
                        new
                        {
                            PermissionId = 6,
                            Description = "Create production schedules",
                            Module = "Production",
                            PermissionName = "Production.Create"
                        },
                        new
                        {
                            PermissionId = 7,
                            Description = "Edit production schedules",
                            Module = "Production",
                            PermissionName = "Production.Edit"
                        },
                        new
                        {
                            PermissionId = 8,
                            Description = "Delete production schedules",
                            Module = "Production",
                            PermissionName = "Production.Delete"
                        },
                        new
                        {
                            PermissionId = 9,
                            Description = "View work orders",
                            Module = "WorkOrders",
                            PermissionName = "WorkOrders.View"
                        },
                        new
                        {
                            PermissionId = 10,
                            Description = "Create work orders",
                            Module = "WorkOrders",
                            PermissionName = "WorkOrders.Create"
                        },
                        new
                        {
                            PermissionId = 11,
                            Description = "Edit work orders",
                            Module = "WorkOrders",
                            PermissionName = "WorkOrders.Edit"
                        },
                        new
                        {
                            PermissionId = 12,
                            Description = "Delete work orders",
                            Module = "WorkOrders",
                            PermissionName = "WorkOrders.Delete"
                        },
                        new
                        {
                            PermissionId = 13,
                            Description = "View inventory",
                            Module = "Inventory",
                            PermissionName = "Inventory.View"
                        },
                        new
                        {
                            PermissionId = 14,
                            Description = "Add inventory items",
                            Module = "Inventory",
                            PermissionName = "Inventory.Create"
                        },
                        new
                        {
                            PermissionId = 15,
                            Description = "Edit inventory",
                            Module = "Inventory",
                            PermissionName = "Inventory.Edit"
                        },
                        new
                        {
                            PermissionId = 16,
                            Description = "Delete inventory items",
                            Module = "Inventory",
                            PermissionName = "Inventory.Delete"
                        },
                        new
                        {
                            PermissionId = 17,
                            Description = "View MRP records",
                            Module = "MRP",
                            PermissionName = "MRP.View"
                        },
                        new
                        {
                            PermissionId = 18,
                            Description = "Run MRP calculations",
                            Module = "MRP",
                            PermissionName = "MRP.Calculate"
                        },
                        new
                        {
                            PermissionId = 19,
                            Description = "View inspections",
                            Module = "Quality",
                            PermissionName = "Quality.View"
                        },
                        new
                        {
                            PermissionId = 20,
                            Description = "Create inspections",
                            Module = "Quality",
                            PermissionName = "Quality.Create"
                        },
                        new
                        {
                            PermissionId = 21,
                            Description = "Edit inspections",
                            Module = "Quality",
                            PermissionName = "Quality.Edit"
                        },
                        new
                        {
                            PermissionId = 22,
                            Description = "View costs",
                            Module = "Costing",
                            PermissionName = "Costing.View"
                        },
                        new
                        {
                            PermissionId = 23,
                            Description = "Add cost entries",
                            Module = "Costing",
                            PermissionName = "Costing.Create"
                        },
                        new
                        {
                            PermissionId = 24,
                            Description = "Edit cost entries",
                            Module = "Costing",
                            PermissionName = "Costing.Edit"
                        },
                        new
                        {
                            PermissionId = 25,
                            Description = "View reports",
                            Module = "Reports",
                            PermissionName = "Reports.View"
                        },
                        new
                        {
                            PermissionId = 26,
                            Description = "Generate reports",
                            Module = "Reports",
                            PermissionName = "Reports.Generate"
                        },
                        new
                        {
                            PermissionId = 27,
                            Description = "View system logs",
                            Module = "System",
                            PermissionName = "System.Logs"
                        },
                        new
                        {
                            PermissionId = 28,
                            Description = "Create backups",
                            Module = "System",
                            PermissionName = "System.Backup"
                        },
                        new
                        {
                            PermissionId = 29,
                            Description = "System configuration",
                            Module = "System",
                            PermissionName = "System.Config"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.ProductionCost", b =>
                {
                    b.Property<int>("CostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CostId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("CostType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("IncurredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("CostId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("ProductionCosts");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.ProductionSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PlannedQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ProductionSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            EndDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQuantity = 100,
                            Priority = "High",
                            ProductName = "Industrial Pump Assembly",
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress"
                        },
                        new
                        {
                            ScheduleId = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            EndDate = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlannedQuantity = 50,
                            Priority = "Medium",
                            ProductName = "Conveyor Belt Module",
                            StartDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Planned"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.QualityInspection", b =>
                {
                    b.Property<int>("InspectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspectionId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InspectorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PassedCount")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SampleSize")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("InspectionId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("QualityInspections");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access across all companies",
                            IsActive = true,
                            RoleName = "Super Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Company owner with full company access",
                            IsActive = true,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages production schedules and planning",
                            IsActive = true,
                            RoleName = "Production Planner"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages inventory and materials",
                            IsActive = true,
                            RoleName = "Inventory Manager"
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages production costing and budgets",
                            IsActive = true,
                            RoleName = "Cost Accountant"
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages work orders on the shop floor",
                            IsActive = true,
                            RoleName = "Shop Floor Supervisor"
                        },
                        new
                        {
                            RoleId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Performs quality inspections and defect tracking",
                            IsActive = true,
                            RoleName = "Quality Control Inspector"
                        },
                        new
                        {
                            RoleId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View-only access to reports and dashboards",
                            IsActive = true,
                            RoleName = "Plant Manager"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermissionId"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RolePermissionId = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 13,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 14,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 15,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 16,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 17,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 18,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 19,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 20,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 21,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 22,
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 23,
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 24,
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 25,
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 26,
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 27,
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 28,
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            RolePermissionId = 29,
                            PermissionId = 29,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@optiflow.com",
                            FirstName = "Super",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$rZJCkpJQ6YBGxQRvpL6Wa.2dHt8sOXEzQqKGJkLKjS5c5B0Wm0FHe",
                            Username = "superadmin"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            AssignedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CompletedQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Priority")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkOrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("WorkOrderNumber")
                        .IsUnique();

                    b.ToTable("WorkOrders");

                    b.HasData(
                        new
                        {
                            WorkOrderId = 1,
                            CompanyId = 1,
                            CompletedQuantity = 30,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProductName = "Industrial Pump Assembly",
                            Quantity = 50,
                            ScheduleId = 1,
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "InProgress",
                            WorkOrderNumber = "WO-2026-001"
                        },
                        new
                        {
                            WorkOrderId = 2,
                            CompanyId = 1,
                            CompletedQuantity = 0,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DueDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Priority = "High",
                            ProductName = "Industrial Pump Assembly",
                            Quantity = 50,
                            ScheduleId = 1,
                            StartDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Pending",
                            WorkOrderNumber = "WO-2026-002"
                        });
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Defect", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.QualityInspection", "QualityInspection")
                        .WithMany("Defects")
                        .HasForeignKey("InspectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QualityInspection");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.InventoryItem", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Company", "Company")
                        .WithMany("InventoryItems")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Casan_IT15_Project.Models.Material", "Material")
                        .WithMany("InventoryItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Material", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Company", "Company")
                        .WithMany("Materials")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.MrpRecord", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Material", "Material")
                        .WithMany("MrpRecords")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Casan_IT15_Project.Models.WorkOrder", "WorkOrder")
                        .WithMany("MrpRecords")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Material");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.ProductionCost", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.WorkOrder", "WorkOrder")
                        .WithMany("ProductionCosts")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.ProductionSchedule", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Company", "Company")
                        .WithMany("ProductionSchedules")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Casan_IT15_Project.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.Navigation("Company");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.QualityInspection", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.WorkOrder", "WorkOrder")
                        .WithMany("QualityInspections")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.RolePermission", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casan_IT15_Project.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.User", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.UserRole", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Casan_IT15_Project.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.WorkOrder", b =>
                {
                    b.HasOne("Casan_IT15_Project.Models.Company", "Company")
                        .WithMany("WorkOrders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Casan_IT15_Project.Models.ProductionSchedule", "ProductionSchedule")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("ProductionSchedule");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Company", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("Materials");

                    b.Navigation("ProductionSchedules");

                    b.Navigation("Users");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Material", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MrpRecords");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.ProductionSchedule", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.QualityInspection", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Casan_IT15_Project.Models.WorkOrder", b =>
                {
                    b.Navigation("MrpRecords");

                    b.Navigation("ProductionCosts");

                    b.Navigation("QualityInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
